STATUS_SUCCESS = 200
STATUS_CONNECTION_FAIL = 501
STATUS_JSON_UNMATCHED = 502
STATUS_OPERATION_UNSUPPORTED = 503
STATUS_PARAMETER_UNMATCHED = 504
STATUS_INFORMATION_UNMATCHED = 505

PARAMETER_RESULT = 'result'
PARAMETER_STATUS = 'status'
PARAMETER_OPERATION = 'opt'
PARAMETER_INFORMATION = 'info'
